from flask import Blueprint, render_template, request, jsonify

from services.code_execution_service import run_python
from services.ai_service import AIService
from routes.main import login_required_api

coding_bp = Blueprint("coding", __name__)
ai_service = AIService()


@coding_bp.route("/coding")
def coding_page():
    return render_template("coding.html")


@coding_bp.route("/api/run-code", methods=["POST"])
def api_run_code():
    data = request.get_json(silent=True) or {}
    language = (data.get("language") or "python").lower()
    code = data.get("code", "")

    if not code.strip():
        return jsonify({"error": "Write some code first."}), 400

    if language != "python":
        return jsonify({
            "error": ("Server-side execution is currently available for Python only. "
                      "JavaScript runs directly in your browser below — other languages "
                      "can be explained/generated by the AI panel but not executed here yet.")
        }), 400

    result = run_python(code)
    return jsonify(result)


@coding_bp.route("/api/code-assist", methods=["POST"])
@login_required_api
def api_code_assist():
    data = request.get_json(silent=True) or {}
    action = data.get("action", "explain_code")
    code = data.get("code", "")
    language = data.get("language", "python")
    if not code.strip():
        return jsonify({"error": "Write some code first."}), 400
    result = ai_service.code_assist(action, code, language)
    if "error" in result:
        return jsonify(result), 503
    return jsonify(result)
